### ISSUE TITLE
console.log does not work when running tests

### ISSUE THREAD

**Issue by daweth** [FrankieIsLost/forge-template#11]
I am expecting `console.log` to work while running `forge test`, but unfortunately I need to do `forge run` for them to work. Is there some script editing that can be done to make this possible?

**Comment by FrankieIsLost** [comment]
try `forge test -vvv`, you need to run tests in verbose mode to see console output

**Comment by StErMi** [comment]
> try `forge test -vvv`, you need to run tests in verbose mode to see console output

I think that (don't know if it's only for new version) it should be `forge test --verbosity 2`

**Comment by daweth** [comment]
thanks, didn't know that.
