### ISSUE TITLE
Should the default license in Contract.sol be 'APGL-3.0-only'?

### ISSUE THREAD

**Issue by metashx** [FrankieIsLost/forge-template#16]
[Solmate](https://github.com/Rari-Capital/solmate/blob/main/LICENSE) is a direct dependency with an [APGL-3.0-only](https://choosealicense.com/licenses/agpl-3.0/) license, but the default license in `Contract.sol` is the Unlicense.
https://github.com/FrankieIsLost/forge-template/blob/152bcf28ffaba7672a4edf938a81967f3c748bd6/src/Contract.sol#L1-L6

While the contract doesn't include any references to solmate by default, users may use it without realizing the license requirements.

APGL-3.0-only is a [copyleft license](https://fossa.com/blog/all-about-copyleft-licenses/) meaning all derivative work must use the same license.

**Comment by metashx** [comment]
I've been BULLIED into closing this issue.

**Comment by wilsoncusack** [comment]
I think a contract that doesn't import or use solmate is not a derivative work
